<div>
    <script
        src="https://giscus.app/client.js"
        data-repo="atomicptr/atomicptr.dev"
        data-repo-id="R_kgDOLCEAgg"
        data-category="Blog"
        data-category-id="DIC_kwDOLCEAgs4CcRWF"
        data-mapping="pathname"
        data-strict="1"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="bottom"
        data-theme="dark"
        data-lang="en"
        data-loading="lazy"
        crossorigin="anonymous"
        async
    >
    </script>
</div>
